# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonprofit',
            name='picture',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
